#!/usr/bin/env bash
#MISE description="Build the Binary"
#MISE outputs=["{{env.OUTDIR}}/{{env.BIN}}"]

build_dir="${OUTDIR:-build}"
app_name="${BIN:-git-vine}"

COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    VERSION="${COMMIT}-dirty"
else
    TAG=$(git describe --exact-match --tags HEAD 2>/dev/null)
    if [ -n "$TAG" ]; then
        VERSION="$TAG"
    else
        VERSION="$COMMIT"
    fi
fi

export CGO_ENABLED=0
export LD_FLAGS="-s -w -X git-vine/cmd.Version=${VERSION}"

echo -e "Generating files..."
go generate ./...
echo

mkdir -p "$build_dir"
[[ -f "$build_dir/$app_name" ]] && rm -f "$build_dir/$app_name"

echo -e "Building..."
go build -trimpath -buildvcs=false -ldflags="${LD_FLAGS}" -o "$build_dir/$app_name" .

#vim:ft=bash:

