#!/usr/bin/env bash
#MISE description="Install the Binary"
#MISE depends = ["build"]

bin="${OUTDIR:-build}/${BIN:-git-wtf}"

install -Dm755 "$bin" "$HOME/.local/bin/$(basename "$bin")"

#vim:ft=bash:

