#!/usr/bin/env bash
#MISE description="Install the Binary"
#MISE depends = ["build"]

bin="${OUTDIR:-build}/${BIN:-git-wtf}"

install -Dm755 "$bin" "$HOME/.local/bin/$(basename "$bin")"

echo "Make sure you have $HOME/.local/bin in your PATH"

#vim:ft=bash:
